CREATE SEQUENCE todo_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE todo_item_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE TODO_USER (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    birthday TIMESTAMP
);

CREATE TABLE TODO_ITEM (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo VARCHAR(255) NOT NULL,
    info VARCHAR(255),
    completion_time TIMESTAMP,
    is_done BOOLEAN DEFAULT FALSE,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES todo_user(id) ON DELETE CASCADE
);

INSERT INTO TODO_USER ( username, first_name, last_name, email, birthday)
VALUES
    ('johndoe', 'John', 'Doe', 'john.doe@example.com', '1990-01-01'),
    ('janedoe', 'Jane', 'Doe', 'jane.doe@example.com', '1992-02-02'),
    ('mike123', 'Mike', 'Smith', 'mike.smith@example.com', '1985-05-15'),
    ('anna_b', 'Anna', 'Brown', 'anna.brown@example.com', '1999-09-09'),
    ('chris_k', 'Chris', 'Knight', 'chris.knight@example.com', '1988-12-25');

INSERT INTO TODO_ITEM (todo, info, completion_time, is_done, user_id)
VALUES
    ('Buy groceries', 'Milk, bread, eggs', '2024-12-10 10:00:00', TRUE, 1),
    ('Complete project', 'Finish the client report', '2024-12-15 17:00:00', FALSE, 1),
    ('Go for a run', 'Morning exercise in the park', '2024-12-07 06:30:00', TRUE, 2),
    ('Read a book', 'Finish reading "Atomic Habits"', NULL, FALSE, 2),
    ('Schedule doctor appointment', 'Annual check-up', '2024-12-20 09:00:00', TRUE, 3),
    ('Plan vacation', 'Choose destination and book tickets', NULL, FALSE, 3),
    ('Clean the house', 'Focus on the kitchen and living room', '2024-12-05 14:00:00', TRUE, 4),
    ('Call parents', 'Catch up with family', '2024-12-08 20:00:00', TRUE, 4),
    ('Organize files', 'Sort documents and photos', '2024-12-06 16:00:00', FALSE, 5),
    ('Learn React', 'Complete tutorial on React basics', NULL, FALSE, 5);

SELECT setval('todo_user_seq', (SELECT MAX(id) FROM TODO_USER));
SELECT setval('todo_item_seq', (SELECT MAX(id) FROM TODO_ITEM));

SELECT * FROM TODO_USER;
SELECT * FROM TODO_ITEM;