name: Build, Test, and Scan with Grype on Master

on:
  push:
    branches: [ master ]

jobs:
  build-test-scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test/

    - name: Build Docker Image
      if: success()
      run: ./gradlew bootBuildImage --imageName=todoapp:${{ github.sha }}

    - name: Scan Docker Image with Grype
      if: success()
      uses: anchore/scan-action@v3
      with:
        image: "todoapp:${{ github.sha }}"
        fail-build: false 
        severity-cutoff: high 
        
    - name: Upload Grype Scan Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: grype-results-image
        path: grype-report.json
